# PyTorch Basics - Working with Tensors
Some exercises to understand the basics of PyTorch working with tensors

## Creating differnet kinds of tensors from lists and numpy arrays

In [311]:
import torch

# Tensors can be created from lists and nested lists:

a = torch.tensor([1 ,2, 3]) # 1D tensor
b = torch.tensor([[1], [2], [3]]) # 2D tensor

print("1D tensor A:", a)
print("2D tensor B:", b, "\n")

1D tensor A: tensor([1, 2, 3])
2D tensor B: tensor([[1],
        [2],
        [3]]) 


In [312]:
a = torch.ones(2, 3) # will throw a type error in numpy
b = torch.ones((2, 3)) # works the same in numpy
torch.equal(a, b)

True

In [313]:
# inspect the dimension of the tensors
print("Dimension of tensor A:", a.dim())
print("Dimension of tensor B:", b.dim(), "\n")
# inspect the size (==shape) of the tensors
print("Shape of tensor A:", a.size())
print("Shape of tensor B:", b.shape, "\n")

Dimension of tensor A: 2
Dimension of tensor B: 2 

Shape of tensor A: torch.Size([2, 3])
Shape of tensor B: torch.Size([2, 3]) 


Note: mytensor.dim() returns len(mytensor.shape) whereas mytensor.shape tells us the number of elements in each dimension

In [314]:

# inspect the data type of the tensors
print("Data type of tensor A:", a.dtype)
print("Data type of tensor B:", b.dtype, "\n")

Data type of tensor A: torch.float32
Data type of tensor B: torch.float32 


In [315]:
a = torch.ones(1,2,3,dtype=torch.long)
b = torch.ones((1,2,3), dtype=torch.float32)
torch.equal(a, b) # will return true because the values of the tensors are the same

True

In [316]:
# Tensors can also be created from NumPy arrays
import numpy as np

my_np_array = np.array([1, 2, 3])
a = torch.tensor(my_np_array) # pass the np array into the tensor function
b = torch.from_numpy(my_np_array) # or use the from_numpy function, the result is the same
print("1D tensor A from numpy array:", a)
print("1D tensor B from numpy array:", b)

1D tensor A from numpy array: tensor([1, 2, 3])
1D tensor B from numpy array: tensor([1, 2, 3])


### Creating special tensors

In [317]:
# creates a 2-dimensional tensor, a 5x5 identity matrix (ones on the diagonal, zeros elsewhere)
identity_tensor = torch.eye(5)
identity_tensor

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [318]:
zero_tensor = torch.zeros(3, 10) # creates a 2-dimensional tensor, a 3x10 matrix filled with zeros
zero_tensor

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [319]:
ones_tensor = torch.ones(5, 2) # creates a 2-dimensional tensor, a 5x2 matrix filled with ones
ones_tensor

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

Note: with any of the above functions, you can specify multiple parameters to create tensors of higher dimensions (in the examples we only created 2D tensors)

In [320]:
random_tensor = torch.rand(2, 2, 3) # creates a 2-dimensional tensor, a 3x4 matrix filled with random numbers between 0 and 1
random_tensor

tensor([[[0.1551, 0.3923, 0.9875],
         [0.4788, 0.3276, 0.3773]],

        [[0.2620, 0.8613, 0.0040],
         [0.1524, 0.7342, 0.1183]]])

In [321]:
random_normal_tensor = torch.randn(20) # creates a 1-dimensional tensor, a 20-element vector filled with random numbers from a normal distribution
random_normal_tensor

tensor([ 1.5868,  0.3860, -0.6176, -0.7524,  0.8798, -1.4360, -0.3200, -0.2827,
        -0.2364, -0.9098,  0.1141,  1.4361, -0.7410,  2.1313, -1.5554, -1.3872,
        -0.5463,  0.6713, -0.4956, -0.4109])

Reminder: Normal distribution means that the mean is 0 and the variance is 1

In [322]:
# we can also create a tensor filled with random integers
random_int_tensor = torch.randint(low=5, high=10, size=(5, 5)) # creates a 2-dimensional tensor, a 5x5 matrix filled with random integers between 0 and 10
random_int_tensor

tensor([[5, 7, 9, 5, 8],
        [7, 8, 6, 7, 6],
        [5, 8, 9, 6, 6],
        [7, 8, 5, 6, 9],
        [6, 6, 9, 8, 7]])

In [323]:
# pytorch also allows to create a tensor filled with a range of numbers
range_tensor = torch.arange(3, 17) # creates a 1-dimensional tensor, a 14-element vector filled with numbers from 3 to 16
range_tensor

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

## Working with tensor metadata

We alredy learned about .dim() .shape and .dtype. Here are some more useful tensor attributes:

In [324]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(my_tensor.numel()) # returns the number of elements in the tensor
print(my_tensor.nelement())

9
9


In [325]:
# Check if cuda is enabled
my_tensor.is_cuda # returns true if the tensor is stored on the GPU

False

In [326]:
# Get the device on which the tensor is stored on (you could have multiple GPUs)
my_tensor.device

device(type='cpu')

# Tensor Types and Casting

PyTorch defines its own data type, which can be used to create tensors. The default data type is float32. You can change the data type of the tensor using the .to() method. 


| Data Type                | dtype                       | CPU tensor       | GPU tensor              |
|--------------------------|-----------------------------|------------------|-------------------------|
| 32-bit floating point    | torch.float32/torch.float   | torch.FloatTensor| torch.cuda.FloatTensor  |
| 64-bit floating point    | torch.float64/torch.double  | torch.DoubleTensor| torch.cuda.DoubleTensor|
| 8-bit integer (signed)   | torch.int16                 | torch.ShortTensor| torch.cuda.ShortTensor  |
| boolean                  | torch.bool                  | torch.BoolTensor | torch.cuda.BoolTensor   |




In [327]:
my_tensor = torch.tensor([1, 1, 1, 1])
print("The dtype of my_tensor is {}".format(my_tensor.dtype))

my_tensor = torch.tensor([1, 2, 3, 4], dtype=torch.float)
print("The dtype of my_tensor is {}".format(my_tensor.dtype))

The dtype of my_tensor is torch.int64
The dtype of my_tensor is torch.float32


In [328]:
# Pytorch has some conevience methods to create tensors with a specific data type
tensor_float32 = torch.FloatTensor([1, 2, 3, 4])
print(tensor_float32.dtype)
tensor_int32 = torch.IntTensor([1, 2, 3, 4])
print(tensor_int32.dtype)
tensor_float64 = torch.DoubleTensor([1, 2, 3, 4])
print(tensor_float64.dtype)
tensor_int64 = torch.LongTensor([1, 2, 3, 4])
print(tensor_int64.dtype)

torch.float32
torch.int32
torch.float64
torch.int64


In [329]:
# Casting tensors to a different data type by calling the .to() method on the tensor
tensor = tensor_float32.to(dtype=torch.int32)
print(tensor.dtype)
tensor = tensor.to(dtype=torch.float32)
print(tensor.dtype)

torch.int32
torch.float32


In [330]:
# It is possible to cast tensors to different devices (CPU or GPU)
tensor = tensor.to(device='cuda')

AssertionError: Torch not compiled with CUDA enabled

In [ ]:
# Or better: :)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
tensor = tensor.to(device)

# Selecting Elements from a Tensor

This works similar to numpy arrays

In [331]:
# reshape a 1D tensor to a 2D tensor
tensor = torch.arange(0, 16)
print("Original tensor:", tensor)
tensor = tensor.reshape((4, 4)) # the product of the dimensions must be equal to the number of elements in the tensor
print("Reshaped tensor:", tensor)

Original tensor: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
Reshaped tensor: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


In [332]:
for i in range(tensor.shape[0]):
    for j in range(tensor.shape[1]):
        print(tensor[i, j], end=" ")
    print()

tensor(0) tensor(1) tensor(2) tensor(3) 
tensor(4) tensor(5) tensor(6) tensor(7) 
tensor(8) tensor(9) tensor(10) tensor(11) 
tensor(12) tensor(13) tensor(14) tensor(15) 


In [333]:
# One can even select rows and columns (!)
print("First row:",tensor[0, :]) # select the first row
print("Seocnd column:", tensor[:, 1]) # select the first column

First row: tensor([0, 1, 2, 3])
Seocnd column: tensor([ 1,  5,  9, 13])


# Selecting elements from a tensor with index_select
This allows us to select elements from a tensor based on the indices we provide

In [334]:
tensor = torch.arange(0, 16).reshape((4,4))
indices = torch.tensor([0, 3]) # select the first and last column 
columns = tensor.index_select(dim=1, index=indices) # dim = 0 for rows, dim is the dimension in which we index
rows =  tensor.index_select(dim=0, index=indices) # dim = 1 for columns, dim is the dimension in which we index
print(tensor)
print(columns)
print(rows)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
tensor([[ 0,  3],
        [ 4,  7],
        [ 8, 11],
        [12, 15]])
tensor([[ 0,  1,  2,  3],
        [12, 13, 14, 15]])


In [335]:
tensor = torch.arange(0,16).reshape(4,4)
print(tensor,"\n")
print(tensor[1,1],"\n") # select a single element
print(tensor[2,:],"\n") # select a row
print(tensor[:,0].reshape(4,1),"\n") # select a column
print(tensor[2:,:2],"\n") # select the lower bottom submatrix (row 3 and 4, column 1 and 2)
print(tensor[0:2,2:4],"\n") # select the top right submatrix (row 0 and 1, column 2 to 3)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]) 

tensor(5) 

tensor([ 8,  9, 10, 11]) 

tensor([[ 0],
        [ 4],
        [ 8],
        [12]]) 

tensor([[ 8,  9],
        [12, 13]]) 

tensor([[2, 3],
        [6, 7]]) 


# Selecting elements from a Tensor with a mask
This is pretty cool, we can create a BoolTensor as a mask to select which elements we want to select from a tensor. 

In [336]:
tensor = torch.arange(0, 9).reshape((3,3))
print(tensor)
mask = torch.BoolTensor([
    [1, 0, 1],  # 1 or True means we select the element
    [0, 1, 0], 
    [1, 0, True]
])
# Alternative way of defining the mask: mask = torch.BoolTensor([1, 0, 1, 0, 1, 1, 1, 0, 1]).reshape(3,3)
print(mask)
selection = torch.masked_select(tensor, mask) # returns a 1D tensor with the elements that are True in the mask
print(selection)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])
tensor([0, 2, 4, 6, 8])


# Reshaping Tensors

In [337]:
tensor = torch.arange(0, 16, dtype=torch.int8)
print("Original tensor:", tensor)
print("Shape of the original tensor:", tensor.shape)
tensor = torch.reshape(tensor, (4,4))
# or tensor = tensor.reshape((4,4))
print("Reshaped tensor:", tensor)
print("Shape of the reshaped tensor:", tensor.shape)

Original tensor: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       dtype=torch.int8)
Shape of the original tensor: torch.Size([16])
Reshaped tensor: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]], dtype=torch.int8)
Shape of the reshaped tensor: torch.Size([4, 4])


In [338]:
tensor = torch.reshape(tensor, (-1, 2)) # the -1 is a placeholder for the dimension that is inferred from the length of the tensor and the other dimensions
print("Reshaped tensor:", tensor)

Reshaped tensor: tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]], dtype=torch.int8)


# Squeeze and un-squeeze

Allows us to remove and add dimensions of size 1 to a tensor.
In numpy expand_dims() and squeeze() are used for the same purpose.

In [339]:
tensor = torch.arange(0, 16).reshape((1, 4, 4))
print("Original tensor:", tensor)
print("Shape of the original tensor:", tensor.shape)
tensor = torch.squeeze(tensor) # removes all dimensions with size 1
print("\nSqueezed tensor:", tensor)
print("Shape of the squeezed tensor:", tensor.shape)

Original tensor: tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]]])
Shape of the original tensor: torch.Size([1, 4, 4])

Squeezed tensor: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
Shape of the squeezed tensor: torch.Size([4, 4])


In [340]:
tensor = torch.arange(0, 16).reshape((4, 4))
print("Original tensor:", tensor)
print("Shape of the original tensor:", tensor.shape)
tensor = torch.unsqueeze(tensor, 1) # adds a dimension at the specified index
print("\nUn-squeezed tensor:", tensor)
print("Shape of the un-squeezed tensor:", tensor.shape)

Original tensor: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
Shape of the original tensor: torch.Size([4, 4])

Un-squeezed tensor: tensor([[[ 0,  1,  2,  3]],

        [[ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11]],

        [[12, 13, 14, 15]]])
Shape of the un-squeezed tensor: torch.Size([4, 1, 4])


In [341]:
tensor = torch.ones((3,1,2,1,2))
print("Shape of the original tensor:", tensor.shape)
tensor = torch.squeeze(tensor, dim=1) # will only work on dimensions of size 1 (in this case the second dimension)
print("Shape of the squeezed tensor:", tensor.shape)
tensor = torch.squeeze(tensor) # remove all remaining dimensions of size 1
print("Shape of the squeezed tensor:", tensor.shape)

Shape of the original tensor: torch.Size([3, 1, 2, 1, 2])
Shape of the squeezed tensor: torch.Size([3, 2, 1, 2])
Shape of the squeezed tensor: torch.Size([3, 2, 2])


# Transposing Tensors

In [342]:
tensor = torch.tensor([[1,2], [0,1]])
print("Original tensor:", tensor)
tensor = torch.transpose(tensor, 0, 1) # swaps the dimensions at index 0 and 1
print("\nTransposed tensor:", tensor)

Original tensor: tensor([[1, 2],
        [0, 1]])

Transposed tensor: tensor([[1, 0],
        [2, 1]])


In [343]:
tensor = torch.zeros(2,3)
print("Shape of the original tensor:", tensor.shape)
tensor = torch.transpose(tensor, 0, 1) # swaps the dimensions at index 0 and 1
print("Shape of the transposed tensor:", tensor.shape)

Shape of the original tensor: torch.Size([2, 3])
Shape of the transposed tensor: torch.Size([3, 2])


# Concatenating Tensors

In [344]:
a = torch.zeros(2,2)
b = torch.ones(2,2)
c = torch.concat([a, b], dim=1) # concat along the columns
d = torch.concat([a, b], dim=0) # concat along the rows
print(a)
print(b)
print(c)
print(d)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0., 1., 1.],
        [0., 0., 1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.]])


# Stacking Tensors

Using torch.cat() and torch.stack().
torch.cat() stacks tensors along an existing dimension, whereas torch.stack() stacks tensors along a new dimension.

In [345]:
a = torch.ones(2,2)
b = torch.zeros(2,2)
print("Tensor A:", a)
print("Shape of tensor A:", a.shape)
print("\nTensor B:", b)
print("Shape of tensor B:", b.shape)
c = torch.stack([a, b], dim=0) # stack along a new dimension
print("\nStacked tensor:", c)
print("Shape of the stacked tensor:", c.shape)
d = torch.cat([a, b], dim=0) # concatenate along an existing dimension (here: rows)
print("\nConcatenated tensor:", d)
print("Shape of the concatenated tensor:", d.shape)
e = torch.cat([a, b], dim=1) # concatenate along an existing dimension (here: rows)
print("\nConcatenated tensor:", e)
print("Shape of the concatenated tensor:", e.shape)

Tensor A: tensor([[1., 1.],
        [1., 1.]])
Shape of tensor A: torch.Size([2, 2])

Tensor B: tensor([[0., 0.],
        [0., 0.]])
Shape of tensor B: torch.Size([2, 2])

Stacked tensor: tensor([[[1., 1.],
         [1., 1.]],

        [[0., 0.],
         [0., 0.]]])
Shape of the stacked tensor: torch.Size([2, 2, 2])

Concatenated tensor: tensor([[1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.]])
Shape of the concatenated tensor: torch.Size([4, 2])

Concatenated tensor: tensor([[1., 1., 0., 0.],
        [1., 1., 0., 0.]])
Shape of the concatenated tensor: torch.Size([2, 4])


# Element-wise operations on tensors

In [346]:
tensor = torch.tensor([1,2,3])
print("Original tensor:", tensor)
tensor += 1 # this adds 1 to each element of the tensor in-place
tensor.add(1) # this returns a new tensor, add does not change the original tensor in-place
tensor.add_(1) # this however changes the original tensor in-place (same as tensor += 1)
print("Tensor after adding 2 to each element:", tensor)
tensor *= 2 
print("Tensor after multiplying each element by 2:", tensor)

Original tensor: tensor([1, 2, 3])
Tensor after adding 2 to each element: tensor([3, 4, 5])
Tensor after multiplying each element by 2: tensor([ 6,  8, 10])


In [347]:
a = torch.arange(0, 4).reshape(2, 2)
b = torch.ones(2,2).reshape(2, 2)
b += 1
c = a + b # element-wise addition
d = a * b # element-wise multiplication
print("Tensor A:", a)
print("Tensor B:", b)
print("Tensor C:", c)
print("Tensor D:", d)

Tensor A: tensor([[0, 1],
        [2, 3]])
Tensor B: tensor([[2., 2.],
        [2., 2.]])
Tensor C: tensor([[2., 3.],
        [4., 5.]])
Tensor D: tensor([[0., 2.],
        [4., 6.]])


# Reduction operations on tensors and comparison operations

In [348]:
# TODO continue here

# Broadcasting tensors
Broadcasting is a powerful mechanism that allows PyTorch to work with tensors of different shapes when performing arithmetic operations.

In [349]:
#TODO show broadcasting example

In [350]:
tensor = torch.arange(0,16)
tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [351]:
tensor.reshape(4, 4) 

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

# Summary

TODO: Add summary

In [352]:
import torch

my_tensor = torch.randn((2, 3, 4), dtype=torch.float)
print("The dtype of my tensor a is:", my_tensor.dtype)
print("The size of my tensor a is:", my_tensor.size())
print("The shape of my tensor a is:", my_tensor.shape)
print("The dims of my tensor a is:", my_tensor.dim())
print("The dims of my tensor a is:", my_tensor.ndim)
print("The number of elements in my tensor is:", my_tensor.numel())
print("My tensor is stored on the GPU:", my_tensor.is_cuda)
print("My tensor is stored on device:", my_tensor.device)



The dtype of my tensor a is: torch.float32
The size of my tensor a is: torch.Size([2, 3, 4])
The shape of my tensor a is: torch.Size([2, 3, 4])
The dims of my tensor a is: 3
The dims of my tensor a is: 3
The number of elements in my tensor is: 24
My tensor is stored on the GPU: False
My tensor is stored on device: cpu


PyTorch offers different data types, choosing the right one is important because it will influence the memory usage and
the performance (and some PyTorch methods have requirements regarding the datatype of the tensor that is passed into them as an argument).

| Data Type              | dtype                      | CPU tensor         | GPU tensor              |
|------------------------|----------------------------|--------------------|-------------------------|
| 32-bit floating point  | torch.float32/torch.float  | torch.FloatTensor  | torch.cuda.FloatTensor  |
| 64-bit floating point  | torch.float64/torch.double | torch.DoubleTensor | torch.cuda.DoubleTensor |
| 8-bit integer (signed) | torch.int16                | torch.ShortTensor  | torch.cuda.ShortTensor  |
| boolean                | torch.bool                 | torch.BoolTensor   | torch.cuda.BoolTensor   |

