# PyTorch Basics - Working with Tensors
Some exercises to understand the basics of PyTorch working with tensors

## Creating differnet kinds of tensors from lists and numpy arrays

In [94]:
import torch

# Tensors can be created from lists and nested lists:

a = torch.tensor([1 ,2, 3]) # 1D tensor
b = torch.tensor([[1], [2], [3]]) # 2D tensor

print("1D tensor A:", a)
print("2D tensor B:", b, "\n")

1D tensor A: tensor([1, 2, 3])
2D tensor B: tensor([[1],
        [2],
        [3]]) 


In [106]:
# inspect the dimension of the tensors
print("Dimension of tensor A:", a.dim())
print("Dimension of tensor B:", b.dim(), "\n")
# inspect the size (==shape) of the tensors
print("Shape of tensor A:", a.size())
print("Shape of tensor B:", b.shape, "\n")

Dimension of tensor A: 1
Dimension of tensor B: 1 

Shape of tensor A: torch.Size([3])
Shape of tensor B: torch.Size([3]) 


Note: mytensor.dim() returns len(mytensor.shape) whereas mytensor.shape tells us the number of elements in each dimension

In [96]:

# inspect the data type of the tensors
print("Data type of tensor A:", a.dtype)
print("Data type of tensor B:", b.dtype, "\n")

Data type of tensor A: torch.int64
Data type of tensor B: torch.int64 


In [97]:
# Tensors can also be created from NumPy arrays
import numpy as np

my_np_array = np.array([1, 2, 3])
a = torch.tensor(my_np_array) # pass the np array into the tensor function
b = torch.from_numpy(my_np_array) # or use the from_numpy function, the result is the same
print("1D tensor A from numpy array:", a)
print("1D tensor B from numpy array:", b)

1D tensor A from numpy array: tensor([1, 2, 3])
1D tensor B from numpy array: tensor([1, 2, 3])


### Creating special tensors

In [98]:
# creates a 2-dimensional tensor, a 5x5 identity matrix (ones on the diagonal, zeros elsewhere)
identity_tensor = torch.eye(5)
identity_tensor

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [99]:
zero_tensor = torch.zeros(3, 10) # creates a 2-dimensional tensor, a 3x10 matrix filled with zeros
zero_tensor

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [100]:
ones_tensor = torch.ones(5, 2) # creates a 2-dimensional tensor, a 5x2 matrix filled with ones
ones_tensor

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

Note: with any of the above functions, you can specify multiple parameters to create tensors of higher dimensions (in the examples we only created 2D tensors)

In [101]:
random_tensor = torch.rand(2, 2, 3) # creates a 2-dimensional tensor, a 3x4 matrix filled with random numbers between 0 and 1
random_tensor

tensor([[[0.4120, 0.4695, 0.2777],
         [0.6588, 0.2601, 0.2044]],

        [[0.7590, 0.7228, 0.6877],
         [0.0785, 0.3292, 0.8320]]])

In [102]:
random_normal_tensor = torch.randn(20) # creates a 1-dimensional tensor, a 20-element vector filled with random numbers from a normal distribution
random_normal_tensor

tensor([ 0.9751, -0.0278, -0.4456,  0.1092,  1.2324,  0.6154, -1.1602,  1.4630,
         0.6622,  0.4169, -0.8514,  1.7354, -0.8758,  0.9820,  0.4704, -1.0366,
         0.7723,  1.8027, -1.0541,  1.9997])

Reminder: Normal distribution means that the mean is 0 and the variance is 1

In [103]:
# we can also create a tensor filled with random integers
random_int_tensor = torch.randint(low=5, high=10, size=(5, 5)) # creates a 2-dimensional tensor, a 5x5 matrix filled with random integers between 0 and 10
random_int_tensor

tensor([[7, 9, 7, 7, 7],
        [9, 7, 7, 6, 6],
        [9, 9, 9, 6, 6],
        [6, 8, 7, 8, 5],
        [7, 8, 5, 9, 5]])

In [104]:
# pytorch also allows to create a tensor filled with a range of numbers
range_tensor = torch.arange(3, 17) # creates a 1-dimensional tensor, a 14-element vector filled with numbers from 3 to 16
range_tensor

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])