# PyTorch Basics - Working with Tensors
Some exercises to understand the basics of PyTorch working with tensors

## Creating differnet kinds of tensors from lists and numpy arrays

In [108]:
import torch

# Tensors can be created from lists and nested lists:

a = torch.tensor([1 ,2, 3]) # 1D tensor
b = torch.tensor([[1], [2], [3]]) # 2D tensor

print("1D tensor A:", a)
print("2D tensor B:", b, "\n")

1D tensor A: tensor([1, 2, 3])
2D tensor B: tensor([[1],
        [2],
        [3]]) 


In [109]:
# inspect the dimension of the tensors
print("Dimension of tensor A:", a.dim())
print("Dimension of tensor B:", b.dim(), "\n")
# inspect the size (==shape) of the tensors
print("Shape of tensor A:", a.size())
print("Shape of tensor B:", b.shape, "\n")

Dimension of tensor A: 1
Dimension of tensor B: 2 

Shape of tensor A: torch.Size([3])
Shape of tensor B: torch.Size([3, 1]) 


Note: mytensor.dim() returns len(mytensor.shape) whereas mytensor.shape tells us the number of elements in each dimension

In [110]:

# inspect the data type of the tensors
print("Data type of tensor A:", a.dtype)
print("Data type of tensor B:", b.dtype, "\n")

Data type of tensor A: torch.int64
Data type of tensor B: torch.int64 


In [111]:
# Tensors can also be created from NumPy arrays
import numpy as np

my_np_array = np.array([1, 2, 3])
a = torch.tensor(my_np_array) # pass the np array into the tensor function
b = torch.from_numpy(my_np_array) # or use the from_numpy function, the result is the same
print("1D tensor A from numpy array:", a)
print("1D tensor B from numpy array:", b)

1D tensor A from numpy array: tensor([1, 2, 3])
1D tensor B from numpy array: tensor([1, 2, 3])


### Creating special tensors

In [112]:
# creates a 2-dimensional tensor, a 5x5 identity matrix (ones on the diagonal, zeros elsewhere)
identity_tensor = torch.eye(5)
identity_tensor

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [113]:
zero_tensor = torch.zeros(3, 10) # creates a 2-dimensional tensor, a 3x10 matrix filled with zeros
zero_tensor

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [114]:
ones_tensor = torch.ones(5, 2) # creates a 2-dimensional tensor, a 5x2 matrix filled with ones
ones_tensor

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

Note: with any of the above functions, you can specify multiple parameters to create tensors of higher dimensions (in the examples we only created 2D tensors)

In [115]:
random_tensor = torch.rand(2, 2, 3) # creates a 2-dimensional tensor, a 3x4 matrix filled with random numbers between 0 and 1
random_tensor

tensor([[[0.5503, 0.0195, 0.9681],
         [0.5661, 0.6106, 0.5195]],

        [[0.7210, 0.1849, 0.1553],
         [0.3442, 0.0896, 0.4959]]])

In [116]:
random_normal_tensor = torch.randn(20) # creates a 1-dimensional tensor, a 20-element vector filled with random numbers from a normal distribution
random_normal_tensor

tensor([ 0.4977, -0.1494, -1.1621,  0.5520, -0.8003, -0.6251, -0.2243, -0.3144,
         0.1240, -0.7619,  0.1678, -1.1305, -0.8303,  0.9611,  1.7411,  1.4667,
         1.5596,  0.3986,  1.2847,  1.0947])

Reminder: Normal distribution means that the mean is 0 and the variance is 1

In [117]:
# we can also create a tensor filled with random integers
random_int_tensor = torch.randint(low=5, high=10, size=(5, 5)) # creates a 2-dimensional tensor, a 5x5 matrix filled with random integers between 0 and 10
random_int_tensor

tensor([[7, 7, 6, 9, 7],
        [6, 9, 9, 6, 5],
        [5, 7, 6, 9, 6],
        [9, 5, 7, 5, 9],
        [9, 7, 6, 5, 5]])

In [118]:
# pytorch also allows to create a tensor filled with a range of numbers
range_tensor = torch.arange(3, 17) # creates a 1-dimensional tensor, a 14-element vector filled with numbers from 3 to 16
range_tensor

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

## Working with tensor metadata

We alredy learned about .dim() .shape and .dtype. Here are some more useful tensor attributes:

In [119]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(my_tensor.numel()) # returns the number of elements in the tensor
print(my_tensor.nelement())

9
9


In [120]:
# Check if cuda is enabled
my_tensor.is_cuda # returns true if the tensor is stored on the GPU

False

In [121]:
# Get the device on which the tensor is stored on (you could have multiple GPUs)
my_tensor.device

device(type='cpu')

# Tensor Types and Casting

PyTorch defines its own data type, which can be used to create tensors. The default data type is float32. You can change the data type of the tensor using the .to() method. 


| Data Type                | dtype                       | CPU tensor       | GPU tensor              |
|--------------------------|-----------------------------|------------------|-------------------------|
| 32-bit floating point    | torch.float32/torch.float   | torch.FloatTensor| torch.cuda.FloatTensor  |
| 64-bit floating point    | torch.float64/torch.double  | torch.DoubleTensor| torch.cuda.DoubleTensor|
| 8-bit integer (signed)   | torch.int16                 | torch.ShortTensor| torch.cuda.ShortTensor  |
| boolean                  | torch.bool                  | torch.BoolTensor | torch.cuda.BoolTensor   |




In [122]:
my_tensor = torch.tensor([1, 1, 1, 1])
print("The dtype of my_tensor is {}".format(my_tensor.dtype))

my_tensor = torch.tensor([1, 2, 3, 4], dtype=torch.float)
print("The dtype of my_tensor is {}".format(my_tensor.dtype))

The dtype of my_tensor is torch.int64
The dtype of my_tensor is torch.float32
