# PyTorch Basics - Working with Tensors
Here are some exercises to understand the basics of PyTorch working with tensors

## Creating tensors

... from lists and numpy arrays.

In [1]:
import os
import torch

# Tensors can be created from lists and nested lists
a = torch.tensor([1 ,2, 3]) # 1D tensor
b = torch.tensor([[1], [2], [3]]) # 2D tensor

print("1D tensor A:", a)
print("2D tensor B:", b, "\n")

1D tensor A: tensor([1, 2, 3])
2D tensor B: tensor([[1],
        [2],
        [3]]) 


In [2]:
a = torch.ones((2, 3)) # works the same in numpy
b = torch.ones(2, 3) # will throw a type error in numpy
torch.equal(a, b)

True

In [3]:
# inspect the dimension of the tensors
print("Dimension of tensor A:", a.dim())
print("Dimension of tensor B:", b.dim(), "\n")
# inspect the size (==shape) of the tensors
print("Shape of tensor A:", a.size())
print("Shape of tensor B:", b.shape, "\n")

Dimension of tensor A: 2
Dimension of tensor B: 2 

Shape of tensor A: torch.Size([2, 3])
Shape of tensor B: torch.Size([2, 3]) 


Note: mytensor.dim() returns len(mytensor.shape) whereas mytensor.shape tells us the number of elements in each dimension

In [4]:
# inspect the data type of the tensors
print("Data type of tensor A:", a.dtype)
print("Data type of tensor B:", b.dtype, "\n")

Data type of tensor A: torch.float32
Data type of tensor B: torch.float32 


In [5]:
a = torch.ones(1,2,3,dtype=torch.long)
b = torch.ones((1,2,3), dtype=torch.float32)
torch.equal(a, b) # will return true because the values of the tensors are the same

True

In [6]:
# Tensors can also be created from NumPy arrays
import numpy as np

my_np_array = np.array([1, 2, 3])
a = torch.tensor(my_np_array) # pass the np array into the tensor function
b = torch.from_numpy(my_np_array) # or use the from_numpy function, the result is the same
print("1D tensor A from numpy array:", a)
print("1D tensor B from numpy array:", b)

1D tensor A from numpy array: tensor([1, 2, 3])
1D tensor B from numpy array: tensor([1, 2, 3])


### Convenience methods for creating special kinds of tensors

In [7]:
# Define a tensor by specifying its shape
shape = (2, 3)
tensor = torch.rand(shape)
print(tensor)
# Create a new tensor with the same shape as an existing tensor
tensor_with_same_dimensions = torch.ones_like(tensor)
print(tensor_with_same_dimensions)

tensor([[0.9531, 0.7774, 0.9178],
        [0.1189, 0.8262, 0.1342]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [8]:
identity_tensor = torch.eye(5) # creates a 2-dimensional tensor, a 5x5 identity matrix (ones on the diagonal, zeros elsewhere)
identity_tensor

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [9]:
zero_tensor = torch.zeros(3, 10) # creates a 2-dimensional tensor, a 3x10 matrix filled with zeros
zero_tensor

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
ones_tensor = torch.ones(5, 2) # creates a 2-dimensional tensor, a 5x2 matrix filled with ones
ones_tensor

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

Note: with any of the above functions, you can specify multiple parameters to create tensors of higher dimensions (in the examples we only created 2D tensors)

In [11]:
random_tensor = torch.rand(2, 2, 3) # creates a 2-dimensional tensor, a 3x4 matrix filled with random numbers between 0 and 1
random_tensor

tensor([[[0.1226, 0.8935, 0.3592],
         [0.3728, 0.1056, 0.6872]],

        [[0.2997, 0.6485, 0.2058],
         [0.4644, 0.8062, 0.9366]]])

In [12]:
random_normal_tensor = torch.randn(20) # creates a 1-dimensional tensor, a 20-element vector filled with random numbers from a normal distribution
random_normal_tensor

tensor([-1.0251,  0.1657,  0.0812,  0.7980, -0.7912, -0.8357,  0.3195,  0.7623,
        -0.5240, -0.8368, -0.8852, -0.5521, -0.9035, -0.2889, -1.7931,  0.7168,
        -1.2081,  1.4115,  0.5351, -0.3454])

Reminder: Normal distribution means that the mean is 0 and the variance is 1

In [13]:
# we can also create a tensor filled with random integers
random_int_tensor = torch.randint(low=5, high=10, size=(5, 5)) # creates a 2-dimensional tensor, a 5x5 matrix filled with random integers between 0 and 10
random_int_tensor

tensor([[6, 6, 8, 5, 6],
        [9, 5, 6, 9, 6],
        [8, 7, 8, 5, 7],
        [8, 7, 7, 7, 8],
        [5, 6, 7, 5, 5]])

In [14]:
# pytorch also allows to create a tensor filled with a range of numbers
range_tensor = torch.arange(3, 17) # creates a 1-dimensional tensor, a 14-element vector filled with numbers from 3 to 16
range_tensor

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

## Working with tensor metadata

We alredy learned about .dim() .shape and .dtype. Here are some more useful tensor attributes:

In [15]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(my_tensor.numel()) # returns the number of elements in the tensor
print(my_tensor.nelement())

9
9


In [16]:
# Check if cuda is enabled
my_tensor.is_cuda # returns true if the tensor is stored on the GPU

False

In [17]:
# Get the device on which the tensor is stored on (you could have multiple GPUs)
my_tensor.device

device(type='cpu')

# Tensor types and type casting

PyTorch defines its own data type, which can be used to create tensors. The default data type is float32. You can change the data type of the tensor using the .to() method. 


| Data Type                | dtype                       | CPU tensor       | GPU tensor              |
|--------------------------|-----------------------------|------------------|-------------------------|
| 32-bit floating point    | torch.float32/torch.float   | torch.FloatTensor| torch.cuda.FloatTensor  |
| 64-bit floating point    | torch.float64/torch.double  | torch.DoubleTensor| torch.cuda.DoubleTensor|
| 8-bit integer (signed)   | torch.int16                 | torch.ShortTensor| torch.cuda.ShortTensor  |
| boolean                  | torch.bool                  | torch.BoolTensor | torch.cuda.BoolTensor   |




In [18]:
my_tensor = torch.tensor([1, 1, 1, 1])
print("The dtype of my_tensor is {}".format(my_tensor.dtype))

my_tensor = torch.tensor([1, 2, 3, 4], dtype=torch.float)
print("The dtype of my_tensor is {}".format(my_tensor.dtype))

The dtype of my_tensor is torch.int64
The dtype of my_tensor is torch.float32


In [19]:
# Pytorch has some conevience methods to create tensors with a specific data type
tensor_float32 = torch.FloatTensor([1, 2, 3, 4])
print(tensor_float32.dtype)
tensor_int32 = torch.IntTensor([1, 2, 3, 4])
print(tensor_int32.dtype)
tensor_float64 = torch.DoubleTensor([1, 2, 3, 4])
print(tensor_float64.dtype)
tensor_int64 = torch.LongTensor([1, 2, 3, 4])
print(tensor_int64.dtype)

torch.float32
torch.int32
torch.float64
torch.int64


In [20]:
# Casting tensors to a different data type by calling the .to() method on the tensor
tensor = tensor_float32.to(dtype=torch.int32)
print(tensor.dtype)
tensor = tensor.to(dtype=torch.float32)
print(tensor.dtype)

torch.int32
torch.float32


In [21]:
# It is possible to cast tensors to different devices (CPU or GPU)
try:
    tensor = tensor.to(device='cuda')
except AssertionError as e:
    print("ERROR:",e)

ERROR: Torch not compiled with CUDA enabled


In [22]:
# Or better, with automatic device detection
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
tensor = tensor.to(device)
print("The device of the tensor is:", tensor.device)

The device of the tensor is: cpu


# Selecting elements from a tensor

This works similar to numpy arrays

In [23]:
# reshape a 1D tensor to a 2D tensor
tensor = torch.arange(0, 16)
print("Original tensor:", tensor)
tensor = tensor.reshape((4, 4)) # the product of the dimensions must be equal to the number of elements in the tensor
print("Reshaped tensor:", tensor)

Original tensor: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
Reshaped tensor: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


In [24]:
for i in range(tensor.shape[0]):
    for j in range(tensor.shape[1]):
        print(tensor[i, j], end=" ")
    print()

tensor(0) tensor(1) tensor(2) tensor(3) 
tensor(4) tensor(5) tensor(6) tensor(7) 
tensor(8) tensor(9) tensor(10) tensor(11) 
tensor(12) tensor(13) tensor(14) tensor(15) 


In [25]:
# One can even select rows and columns (!)
print("First row:",tensor[0, :]) # select the first row
print("Seocnd column:", tensor[:, 1]) # select the first column

First row: tensor([0, 1, 2, 3])
Seocnd column: tensor([ 1,  5,  9, 13])


# Selecting elements from a tensor with index_select
This allows us to select elements from a tensor based on the indices we provide

In [26]:
tensor = torch.arange(0, 16).reshape((4,4))
indices = torch.tensor([0, 3]) # select the first and last column 
columns = tensor.index_select(dim=1, index=indices) # dim = 0 for rows, dim is the dimension in which we index
rows =  tensor.index_select(dim=0, index=indices) # dim = 1 for columns, dim is the dimension in which we index
print(tensor)
print(columns)
print(rows)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
tensor([[ 0,  3],
        [ 4,  7],
        [ 8, 11],
        [12, 15]])
tensor([[ 0,  1,  2,  3],
        [12, 13, 14, 15]])


In [27]:
tensor = torch.arange(0,16).reshape(4,4)
print(tensor,"\n")
print(tensor[1,1],"\n") # select a single element
print(tensor[2,:],"\n") # select a row
print(tensor[:,0].reshape(4,1),"\n") # select a column
print(tensor[2:,:2],"\n") # select the lower bottom submatrix (row 3 and 4, column 1 and 2)
print(tensor[0:2,2:4],"\n") # select the top right submatrix (row 0 and 1, column 2 to 3)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]) 

tensor(5) 

tensor([ 8,  9, 10, 11]) 

tensor([[ 0],
        [ 4],
        [ 8],
        [12]]) 

tensor([[ 8,  9],
        [12, 13]]) 

tensor([[2, 3],
        [6, 7]]) 


# Selecting elements from a tensor with a mask
This is pretty cool, we can create a BoolTensor as a mask to select which elements we want to select from a tensor. 

In [28]:
tensor = torch.arange(0, 9).reshape((3,3))
print(tensor)
mask = torch.BoolTensor([
    [1, 0, 1],  # 1 or True means we select the element
    [0, 1, 0], 
    [1, 0, True]
])
# Alternative way of defining the mask: mask = torch.BoolTensor([1, 0, 1, 0, 1, 1, 1, 0, 1]).reshape(3,3)
print(mask)
selection = torch.masked_select(tensor, mask) # returns a 1D tensor with the elements that are True in the mask
print(selection)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])
tensor([0, 2, 4, 6, 8])


# Reshaping tensors

In [29]:
tensor = torch.arange(0, 16, dtype=torch.int8)
print("Original tensor:", tensor)
print("Shape of the original tensor:", tensor.shape)
tensor = torch.reshape(tensor, (4,4))
# or tensor = tensor.reshape((4,4))
print("Reshaped tensor:", tensor)
print("Shape of the reshaped tensor:", tensor.shape)

Original tensor: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       dtype=torch.int8)
Shape of the original tensor: torch.Size([16])
Reshaped tensor: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]], dtype=torch.int8)
Shape of the reshaped tensor: torch.Size([4, 4])


In [30]:
tensor = torch.reshape(tensor, (-1, 2)) # the -1 is a placeholder for the dimension that is inferred from the length of the tensor and the other dimensions
print("Reshaped tensor:", tensor)

Reshaped tensor: tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]], dtype=torch.int8)


# Squeezing and un-squeezing tensors

Allows us to remove and add dimensions of size 1 to a tensor.
In numpy expand_dims() and squeeze() are used for the same purpose.

In [31]:
tensor = torch.arange(0, 16).reshape((1, 4, 4))
print("Original tensor:", tensor)
print("Shape of the original tensor:", tensor.shape)
tensor = torch.squeeze(tensor) # removes all dimensions with size 1
print("\nSqueezed tensor:", tensor)
print("Shape of the squeezed tensor:", tensor.shape)

Original tensor: tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]]])
Shape of the original tensor: torch.Size([1, 4, 4])

Squeezed tensor: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
Shape of the squeezed tensor: torch.Size([4, 4])


In [32]:
tensor = torch.arange(0, 16).reshape((4, 4))
print("Original tensor:", tensor)
print("Shape of the original tensor:", tensor.shape)
tensor = torch.unsqueeze(tensor, 1) # adds a dimension at the specified index
print("\nUn-squeezed tensor:", tensor)
print("Shape of the un-squeezed tensor:", tensor.shape)

Original tensor: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
Shape of the original tensor: torch.Size([4, 4])

Un-squeezed tensor: tensor([[[ 0,  1,  2,  3]],

        [[ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11]],

        [[12, 13, 14, 15]]])
Shape of the un-squeezed tensor: torch.Size([4, 1, 4])


In [33]:
tensor = torch.ones((3,1,2,1,2))
print("Shape of the original tensor:", tensor.shape)
tensor = torch.squeeze(tensor, dim=1) # will only work on dimensions of size 1 (in this case the second dimension)
print("Shape of the squeezed tensor:", tensor.shape)
tensor = torch.squeeze(tensor) # remove all remaining dimensions of size 1
print("Shape of the squeezed tensor:", tensor.shape)

Shape of the original tensor: torch.Size([3, 1, 2, 1, 2])
Shape of the squeezed tensor: torch.Size([3, 2, 1, 2])
Shape of the squeezed tensor: torch.Size([3, 2, 2])


# Transposing tensors

In [34]:
tensor = torch.tensor([[1,2], [0,1]])
print("Original tensor:", tensor)
tensor = torch.transpose(tensor, 0, 1) # swaps the dimensions at index 0 and 1
print("\nTransposed tensor:", tensor)

Original tensor: tensor([[1, 2],
        [0, 1]])

Transposed tensor: tensor([[1, 0],
        [2, 1]])


In [35]:
tensor = torch.zeros(2,3)
print("Shape of the original tensor:", tensor.shape)
tensor = torch.transpose(tensor, 0, 1) # swaps the dimensions at index 0 and 1
print("Shape of the transposed tensor:", tensor.shape)

Shape of the original tensor: torch.Size([2, 3])
Shape of the transposed tensor: torch.Size([3, 2])


# Concatenating tensors

In [36]:
a = torch.zeros(2,2)
b = torch.ones(2,2)
c = torch.concat([a, b], dim=1) # concat along the columns
d = torch.concat([a, b], dim=0) # concat along the rows
print(a)
print(b)
print(c)
print(d)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0., 1., 1.],
        [0., 0., 1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.]])


# Stacking tensors

Using torch.cat() and torch.stack().
torch.cat() stacks tensors along an existing dimension, whereas torch.stack() stacks tensors along a new dimension.

In [37]:
a = torch.ones(2,2)
b = torch.zeros(2,2)
print("Tensor A:", a)
print("Shape of tensor A:", a.shape)
print("\nTensor B:", b)
print("Shape of tensor B:", b.shape)
c = torch.stack([a, b], dim=0) # stack along a new dimension
print("\nStacked tensor:", c)
print("Shape of the stacked tensor:", c.shape)
d = torch.cat([a, b], dim=0) # concatenate along an existing dimension (here: rows)
print("\nConcatenated tensor:", d)
print("Shape of the concatenated tensor:", d.shape)
e = torch.cat([a, b], dim=1) # concatenate along an existing dimension (here: rows)
print("\nConcatenated tensor:", e)
print("Shape of the concatenated tensor:", e.shape)

Tensor A: tensor([[1., 1.],
        [1., 1.]])
Shape of tensor A: torch.Size([2, 2])

Tensor B: tensor([[0., 0.],
        [0., 0.]])
Shape of tensor B: torch.Size([2, 2])

Stacked tensor: tensor([[[1., 1.],
         [1., 1.]],

        [[0., 0.],
         [0., 0.]]])
Shape of the stacked tensor: torch.Size([2, 2, 2])

Concatenated tensor: tensor([[1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.]])
Shape of the concatenated tensor: torch.Size([4, 2])

Concatenated tensor: tensor([[1., 1., 0., 0.],
        [1., 1., 0., 0.]])
Shape of the concatenated tensor: torch.Size([2, 4])


# Element-wise operations on tensors

In [38]:
tensor = torch.tensor([1,2,3])
print("Original tensor:", tensor)
tensor += 1 # this adds 1 to each element of the tensor in-place
tensor.add(1) # this returns a new tensor, add does not change the original tensor in-place
tensor.add_(1) # this however changes the original tensor in-place (same as tensor += 1)
print("Tensor after adding 2 to each element:", tensor)
tensor *= 2 
print("Tensor after multiplying each element by 2:", tensor)

Original tensor: tensor([1, 2, 3])
Tensor after adding 2 to each element: tensor([3, 4, 5])
Tensor after multiplying each element by 2: tensor([ 6,  8, 10])


In [39]:
a = torch.arange(0, 4).reshape(2, 2)
b = torch.ones(2,2).reshape(2, 2)
b += 1
c = a + b # element-wise addition
d = a * b # element-wise multiplication
print("Tensor A:", a)
print("Tensor B:", b)
print("Tensor C:", c)
print("Tensor D:", d)

Tensor A: tensor([[0, 1],
        [2, 3]])
Tensor B: tensor([[2., 2.],
        [2., 2.]])
Tensor C: tensor([[2., 3.],
        [4., 5.]])
Tensor D: tensor([[0., 2.],
        [4., 6.]])


# Reduction and comparison operations

PyTorch offers a variety of reduction operations that can be applied to tensors.
Unless the argument dim is specified, the operation is applied to all elements of the tensor.

| Function | Description |
|----------|-------------|
| mean()   | Computes the mean of all elements in the tensor |
| sum()    | Computes the sum of all elements in the tensor |
| max()    | Returns the maximum value in the tensor |
| min()    | Returns the minimum value in the tensor |
| argmax() | Returns the index of the maximum value in the tensor |
| argmin() | Returns the index of the minimum value in the tensor |
| eq()     | Element-wise comparison, returns a tensor with True where the elements are equal |
| lt()     | Element-wise comparison, returns a tensor with True where the elements are less than |
| gt()     | Element-wise comparison, returns a tensor with True where the elements are greater than |
| le()     | Element-wise comparison, returns a tensor with True where the elements are less than or equal |
| ge()     | Element-wise comparison, returns a tensor with True where the elements are greater than or equal |
| ne()     | Element-wise comparison, returns a tensor with True where the elements are not equal |
| median() | Returns the median of all elements in the tensor |
| mode()   | Returns the mode of all elements in the tensor |
| std()    | Returns the standard deviation of all elements in the tensor |
| var()    | Returns the variance of all elements in the tensor |
| all()    | Returns True if all elements in the tensor are True |
| any()    | Returns True if any element in the tensor is True |
| prod()   | Returns the product of all elements in the tensor |
| unique() | Returns the unique elements in the tensor |
| cumsum() | Returns the cumulative sum of the elements in the tensor |
| cumprod()| Returns the cumulative product of the elements in the tensor |


In [40]:
tensor = torch.arange(0, 9, dtype=torch.float32).reshape(3,3)
print("Original tensor:", tensor)
print("\ntorch.mean(tensor) is:",torch.mean(tensor))
print("\ntorch.mean(tensor, dim=0) is:",torch.mean(tensor, dim=0)) # returns the mean of the elements in the tensor for each column
print("\ntorch.mean(tensor, dim=1) is:",torch.mean(tensor, dim=1)) # returns the mean of the elements in the tensor for each row
print("\ntorch.sum(tensor) is:",torch.sum(tensor))
print("\ntorch.max(tensor) is:",torch.max(tensor))
print("\ntorch.min(tensor) is:",torch.min(tensor))
print("\ntorch.median(tensor) is:",torch.median(tensor))
print("\ntorch.mode(tensor) is:",torch.mode(tensor))
print("\ntorch.std(tensor) is:",torch.std(tensor))
print("\ntorch.var(tensor) is:",torch.var(tensor))
print("\ntorch.all(tensor) is:",torch.all(tensor))
print("\ntorch.prod(tensor) is:",torch.prod(tensor)) # returns the product of all elements in the tensor
print("\ntorch.cumsum(tensor, dim=1) is:",torch.cumsum(tensor, dim=1)) # returns the cumulative sum of the elements in the tensor for each row
print("\ntorch.cumprod(tensor, dim=0) is:",torch.cumprod(tensor, dim=0)) # returns the cumulative product of the elements in the tensor for each column



Original tensor: tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

torch.mean(tensor) is: tensor(4.)

torch.mean(tensor, dim=0) is: tensor([3., 4., 5.])

torch.mean(tensor, dim=1) is: tensor([1., 4., 7.])

torch.sum(tensor) is: tensor(36.)

torch.max(tensor) is: tensor(8.)

torch.min(tensor) is: tensor(0.)

torch.median(tensor) is: tensor(4.)

torch.mode(tensor) is: torch.return_types.mode(
values=tensor([0., 3., 6.]),
indices=tensor([0, 0, 0]))

torch.std(tensor) is: tensor(2.7386)

torch.var(tensor) is: tensor(7.5000)

torch.all(tensor) is: tensor(False)

torch.prod(tensor) is: tensor(0.)

torch.cumsum(tensor, dim=1) is: tensor([[ 0.,  1.,  3.],
        [ 3.,  7., 12.],
        [ 6., 13., 21.]])

torch.cumprod(tensor, dim=0) is: tensor([[ 0.,  1.,  2.],
        [ 0.,  4., 10.],
        [ 0., 28., 80.]])


In [41]:
tensor = torch.LongTensor([0,1,2,0]).reshape(2,2)
print("Original tensor:", tensor)
print("\ntorch.argmax(tensor) is:",torch.argmax(tensor))
print("\ntorch.argmin(tensor) is:",torch.argmin(tensor))
print("\ntorch.any(tensor) is:",torch.any(tensor)) # returns True if any element in the tensor is True
print("\ntorch.unique(tensor) is:",torch.unique(tensor)) # returns the unique elements in the tensor

Original tensor: tensor([[0, 1],
        [2, 0]])

torch.argmax(tensor) is: tensor(2)

torch.argmin(tensor) is: tensor(0)

torch.any(tensor) is: tensor(True)

torch.unique(tensor) is: tensor([0, 1, 2])


In [42]:
tensor = torch.arange(0, 9, dtype=torch.float32).reshape(3,3)
# copy tensor
another_tensor = tensor.clone() # creates a copy of the tensor
another_tensor[0,0] = 1
print("Original tensor:", tensor)
print("\nAnother tensor:", another_tensor)
print("\ntensor.eq() is:",tensor.eq(another_tensor))
print("\ntensor.lt() is:",tensor.lt(another_tensor))
print("\ntensor.gt() is:",tensor.gt(another_tensor))
print("\ntensor.le() is:",tensor.le(another_tensor))
print("\ntensor.ge() is:",tensor.ge(another_tensor))
print("\ntensor.ne() is:",tensor.ne(another_tensor))


Original tensor: tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

Another tensor: tensor([[1., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

tensor.eq() is: tensor([[False,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])

tensor.lt() is: tensor([[ True, False, False],
        [False, False, False],
        [False, False, False]])

tensor.gt() is: tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

tensor.le() is: tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

tensor.ge() is: tensor([[False,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])

tensor.ne() is: tensor([[ True, False, False],
        [False, False, False],
        [False, False, False]])


In [43]:
a = torch.randn((3,4))
print("The original tensor is \n {}".format(a))
print("The comparison between a tensor and a single value.\n")
b = torch.lt(a, 0.5)
print("The element is less than 0.5 \n {}".format(b))
c = torch.randn((3, 4))
print("The comparison between two tensors.\n")
d = torch.gt(a, c)
print("The comparison result between tesnor a and c \n {}".format(d))

The original tensor is 
 tensor([[-0.5301,  0.9670, -1.0972, -0.2619],
        [ 0.2033,  0.0690,  0.4892,  1.9843],
        [ 0.8123, -1.3435,  0.1734, -1.0844]])
The comparison between a tensor and a single value.

The element is less than 0.5 
 tensor([[ True, False,  True,  True],
        [ True,  True,  True, False],
        [False,  True,  True,  True]])
The comparison between two tensors.

The comparison result between tesnor a and c 
 tensor([[False,  True, False, False],
        [ True,  True,  True,  True],
        [ True, False, False, False]])


# Matrix-matrix, matrix-vector and vector-vector multiplications

Matrix vector multiplication can be done using the mv() function or the @ operator.
Similarly matrix matrix multiplication can be done using the mm() function or the @ operator.
The dot product of two tensors can be calculated using the dot() function.

Note:

torch.mv requires a 2D tensor and a 1D tensor.
torch.mm requires two tensors to have the same dimensions (mm does not broadcast).
torch.dot requires the two tensors to be 1D tensors of the same length.
torch.matmul can be used for matrix multiplication and matrix-vector multiplication (matmul does broadcast).


In [44]:
matrix = torch.ones(2,3) # 2x3 matrix
print("Matrix:", matrix)
vector = torch.tensor([1, 1, 2], dtype=torch.float32) # dimension must match the number of columns in the matrix
print("Vector:", vector)
result = torch.mv(matrix, vector) # matrix-vector multiplication, requires float data type
print("Result of matrix-vector multiplication:", result)

result = matrix @ vector # matrix-vector multiplication using the @ operator
print("Result of matrix-vector multiplication using the @ operator:", result)

Matrix: tensor([[1., 1., 1.],
        [1., 1., 1.]])
Vector: tensor([1., 1., 2.])
Result of matrix-vector multiplication: tensor([4., 4.])
Result of matrix-vector multiplication using the @ operator: tensor([4., 4.])


In [45]:
A = torch.ones(2,3) # 2x3 matrix
B = torch.ones(3,2)
print("Matrix A:", A, A.shape)
print("\nMatrix B:", B, B.shape)
result = torch.mm(A, B)
print("\nResult of matrix-matrix multiplication:", result)
result = A @ B
print("\nResult of matrix-matrix multiplication using the @ operator:", result)

Matrix A: tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.Size([2, 3])

Matrix B: tensor([[1., 1.],
        [1., 1.],
        [1., 1.]]) torch.Size([3, 2])

Result of matrix-matrix multiplication: tensor([[3., 3.],
        [3., 3.]])

Result of matrix-matrix multiplication using the @ operator: tensor([[3., 3.],
        [3., 3.]])


In [46]:
v = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
print("Vector v:", v, v.shape)
u = torch.ones(4) * 2
print("Vector u:", u, u.shape)
result = torch.dot(v, u) # dot product of two tensors
print("Result of dot product:", result)

Vector v: tensor([1., 2., 3., 4.]) torch.Size([4])
Vector u: tensor([2., 2., 2., 2.]) torch.Size([4])
Result of dot product: tensor(20.)


# Loading and saving tensors from disk


In [47]:
tensor = torch.arange(0,15)
filename = 'tensors.pt'
torch.save(tensor, filename) # save the tensor to a file
loaded_tensor = torch.load(filename) # load the tensor from a file
print("Loaded tensor: {}".format(loaded_tensor))

Loaded tensor: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])


In [48]:
# Save a list of tensors
tensors = [
    torch.arange(0, 5),
    torch.ones(3, 3),
    torch.zeros(5, 5)
]
torch.save(tensors, filename) # save a list of tensors to a file
loaded_tensors = torch.load(filename) # load the list of tensors from a file
print("Loaded {} tensors:\n\n{}".format(len(loaded_tensors),loaded_tensors))

Loaded 3 tensors:

[tensor([0, 1, 2, 3, 4]), tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]), tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])]


In [49]:
# Save a map of tensors
tensors = {
    'arange': torch.arange(0, 5),
    'ones': torch.ones(3, 3),
    'zeros': torch.zeros(5, 5)
}
torch.save(tensors, filename) # save a list of tensors to a file
loaded_tensors = torch.load(filename) # load the list of tensors from a file
print("Loaded {} tensors:\n\n{}".format(len(loaded_tensors),loaded_tensors))

Loaded 3 tensors:

{'arange': tensor([0, 1, 2, 3, 4]), 'ones': tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]), 'zeros': tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])}


In [50]:
import os
if os.path.exists(filename):
    os.remove(filename)
    print("Removed '{}' from disk.".format(filename))
else:
    print("File '{}' does not exist.".format(filename))

Removed 'tensors.pt' from disk.


# The concept of broadcasting
Broadcasting is a powerful mechanism that allows PyTorch to work with tensors of different shapes when performing arithmetic operations.

Broadcasting refers to the method used to apply arithmetic operations to arrays of differing shapes. Under specific conditions, the smaller array is "broadcast" over the larger one to ensure their shapes are compatible for the operations. Here is an example:

In [51]:
a = torch.rand([10, 3, 4]) # This tensor can be interpreted as a batch of 10 3x4 matrices
b = torch.rand([4, 6])
print("Shape of tensor A:", a.shape)
print("Shape of tensor B:", b.shape)
"""
To perform the matrix multiplication, PyTorch broadcasts the b tensor to match the batch size of a. This means tensor b is implicitly expanded to [10, 4, 6] without actually copying the data but by conceptually replicating b across the batch dimension.
"""
result = torch.matmul(a, b) 
print("Shape of the result tensor:", result.shape)

Shape of tensor A: torch.Size([10, 3, 4])
Shape of tensor B: torch.Size([4, 6])
Shape of the result tensor: torch.Size([10, 3, 6])


In [52]:
tensor = torch.arange(0,16)
tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [53]:
tensor.reshape(4, 4) 

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

# Summary

The following is a summary of the most important functions and methods we have learned in this notebook:

In [54]:
import torch

my_tensor = torch.randn((2, 3, 4), dtype=torch.float)
print("The dtype of my tensor a is:", my_tensor.dtype)
print("The size of my tensor a is:", my_tensor.size())
print("The shape of my tensor a is:", my_tensor.shape)
print("The dims of my tensor a is:", my_tensor.dim())
print("The dims of my tensor a is:", my_tensor.ndim)
print("The number of elements in my tensor is:", my_tensor.numel())
print("My tensor is stored on the GPU:", my_tensor.is_cuda)
print("My tensor is stored on device:", my_tensor.device)

The dtype of my tensor a is: torch.float32
The size of my tensor a is: torch.Size([2, 3, 4])
The shape of my tensor a is: torch.Size([2, 3, 4])
The dims of my tensor a is: 3
The dims of my tensor a is: 3
The number of elements in my tensor is: 24
My tensor is stored on the GPU: False
My tensor is stored on device: cpu


PyTorch offers different data types, choosing the right one is important because it will influence the memory usage and
the performance (and some PyTorch methods have requirements regarding the datatype of the tensor that is passed into them as an argument).

| Data Type              | dtype                      | CPU tensor         | GPU tensor              |
|------------------------|----------------------------|--------------------|-------------------------|
| 32-bit floating point  | torch.float32/torch.float  | torch.FloatTensor  | torch.cuda.FloatTensor  |
| 64-bit floating point  | torch.float64/torch.double | torch.DoubleTensor | torch.cuda.DoubleTensor |
| 8-bit integer (signed) | torch.int16                | torch.ShortTensor  | torch.cuda.ShortTensor  |
| boolean                | torch.bool                 | torch.BoolTensor   | torch.cuda.BoolTensor   |

